<!DOCTYPE html>
<html lang="en" data-theme=""><head>
    <title> Sam Passmore | Ancestral state reconstruction with INLA </title>
    
    
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-63HEHQ31FH"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());
    
        gtag('config', 'G-63HEHQ31FH');
    </script>
    
    
    <meta charset="utf-8"><meta name="generator" content="Hugo 0.101.0" /><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
    <meta name="description" content="Call me Sam">
    
    <link rel="stylesheet"
          href="https://www.sampassmore.com/css/style.min.0c643de4008adca329f7a2d616ce308cca99d4ef45e4cca307323e7857910194.css"
          integrity="sha256-DGQ95ACK3KMp96LWFs4wjMqZ1O9F5MyjBzI&#43;eFeRAZQ="
          crossorigin="anonymous"
          type="text/css">
    
    <link rel="stylesheet"
        href="https://www.sampassmore.com/css/markupHighlight.min.f798cbda9aaa38f89eb38be6414bd082cfd71a6780375cbf67b6d2fb2b96491e.css"
        integrity="sha256-95jL2pqqOPies4vmQUvQgs/XGmeAN1y/Z7bS&#43;yuWSR4="
        crossorigin="anonymous"
        type="text/css">
    
        
        
        <link rel="stylesheet"
        href="https://www.sampassmore.com/css/custom.min.e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css"
        integrity="sha256-47DEQpj8HBSa&#43;/TImW&#43;5JCeuQeRkm5NMpJWZG3hSuFU="
        crossorigin="anonymous"
        media="screen" />
    
        
        
        <link rel="stylesheet"
        href="https://www.sampassmore.com/css/styles.min.0cd54c12a27d64a08b939f7302a7ea69900f769ea99c0351026f02ccaf421a4f.css"
        integrity="sha256-DNVMEqJ9ZKCLk59zAqfqaZAPdp6pnANRAm8CzK9CGk8="
        crossorigin="anonymous"
        media="screen" />
    
    <link rel="stylesheet" 
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" 
    integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" 
    crossorigin="anonymous" />
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
    
    
    <link rel="shortcut icon" href="https://www.sampassmore.com/favicons/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" sizes="180x180" href="https://www.sampassmore.com/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="https://www.sampassmore.com/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="https://www.sampassmore.com/favicons/favicon-16x16.png">

    <link rel="canonical" href="https://www.sampassmore.com/post/2023-02-10-ancestral-state-reconstruction-with-inla/">

    
    
    
    
    <script type="text/javascript"
            src="https://www.sampassmore.com/js/anatole-header.min.df804b63b5bd8474ea0756ea874bc8f1e92552708cc6ea43aa0d76981dc419f9.js"
            integrity="sha256-34BLY7W9hHTqB1bqh0vI8eklUnCMxupDqg12mB3EGfk="
            crossorigin="anonymous"></script>


    
        
        
        <script type="text/javascript"
                src="https://www.sampassmore.com/js/anatole-theme-switcher.min.3829579c725749492568b0e6fa9da3012a7fc37fd291b4fd79e33c1df5d8a34a.js"
                integrity="sha256-OClXnHJXSUklaLDm&#43;p2jASp/w3/SkbT9eeM8HfXYo0o="
                crossorigin="anonymous"></script>
    
    <meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:image" content="https://www.sampassmore.com/105"/>

<meta name="twitter:title" content="Ancestral state reconstruction with INLA"/>
<meta name="twitter:description" content="A common task in phylogenetics is ancestral state reconstruction. There are a number of tools to do this inside and outside R."/>


    
    <meta property="og:title" content="Ancestral state reconstruction with INLA" />
<meta property="og:description" content="A common task in phylogenetics is ancestral state reconstruction. There are a number of tools to do this inside and outside R." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://www.sampassmore.com/post/2023-02-10-ancestral-state-reconstruction-with-inla/" /><meta property="og:image" content="https://www.sampassmore.com/105"/><meta property="article:section" content="post" />
<meta property="article:published_time" content="2023-03-03T00:00:00+00:00" />
<meta property="article:modified_time" content="2023-03-03T00:00:00+00:00" /><meta property="og:site_name" content="Dr Sam Passmore" />


</head>
<body><div class="sidebar animated fadeInDown ">
    <div class="logo-title">
        <div class="title">
            <img src="https://www.sampassmore.com/images/profile.jpg" alt="profile picture">
            <h3 title=""><a href="/">Dr Sam Passmore</a></h3>
            <div class="description">
                <p>Call me Sam</p>
            </div>
        </div>
    </div>
    <ul class="social-links">
        
            <li>
                <a href="https://twitter.com/SamPassmore_" rel="me" aria-label="Twitter">
                    <i class="fab fa-twitter fa-2x" aria-hidden="true"></i>
                </a>
            </li>
        
            <li>
                <a href="https://scholar.google.co.uk/citations?user=zrjq62QAAAAJ&amp;hl=en" rel="me" aria-label="Google Scholar">
                    <i class="ai ai-google-scholar-square fa-2x" aria-hidden="true"></i>
                </a>
            </li>
        
            <li>
                <a href="https://github.com/SamPassmore" rel="me" aria-label="GitHub">
                    <i class="fab fa-github fa-2x" aria-hidden="true"></i>
                </a>
            </li>
        
            <li>
                <a href="mailto:samuel.passmore@anu.edu.au" rel="me" aria-label="e-mail">
                    <i class="fas fa-envelope fa-2x" aria-hidden="true"></i>
                </a>
            </li>
        
    </ul>
    <div class="footer">
        <div class="by_farbox">&copy; Sam Passmore  2025 </div>
    </div>
</div>
<div class="main">
    <div class="page-top  animated fadeInDown ">
    <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
    </a>
    <ul class="nav" id="navMenu">
        
        
            
            <li><a 
                   href="/"
                        
                   title="">Home</a></li>
        
            
            <li><a 
                   href="/post/"
                        
                   title="">Posts</a></li>
        
            
            <li><a 
                   href="/publications/"
                        
                   title="">Publications</a></li>
        
        
        
            <li class="theme-switch-item">
                <a class="theme-switch" title="Switch Theme">
                    <i class="fas fa-adjust fa-fw" aria-hidden="true"></i>
                </a>
            </li>
        
    </ul>
</div>

    <div class="autopagerize_page_element">
        <div class="content">
    <div class="post  animated fadeInDown ">
        <div class="post-content">
            
            <div class="post-title">
                <h3>Ancestral state reconstruction with INLA</h3>
                
                    <div class="info">
                        <em class="fas fa-calendar-day"></em>
                        <span class="date"> Fri, Mar 3, 2023 
                                           </span>
                        <em class="fas fa-stopwatch"></em>
                        <span class="reading-time">5-minute read</span>
                    </div>
                
            </div>

            


<p>A common task in phylogenetics is ancestral state reconstruction. There are a number of tools to do this inside and outside R. Some noteable R examples are: using <a href="http://ape-package.ird.fr/">ape</a> (which I will use for comparison today), and <a href="http://www.phytools.org/Rbook/">phytools</a>, which are both frequentist implementations. Bayesian implementations are available using <a href="http://www.evolution.reading.ac.uk/BayesTraitsV4.0.0/BayesTraitsV4.0.0.html">BayesTraits</a>. This post shows how to implement a Bayesian ancestral state reconstruction approach using the R modelling package INLA. As with my previous INLA post, the process is a result of discussions with <a href="https://twitter.com/ecologician">Russell Dinnage</a>, and any mistakes are surely introduced by me.</p>
<p>For starters. I first simulate a simple ancestral state result using ape, where the ancestral state of the phylogeny is 5:</p>
<pre class="r"><code>library(ape)

# Simulate a tree for n taxa. 
n = 100 
sim.tree = rcoal(n = n)

# Simulate a continuous trait along that tree, where the ancestral state is 5
# With a standard deviation of 1.5 (sigma)
y = rTraitCont(phy = sim.tree, root.value = 5, sigma = 1.5)

# Calculate the ancestral state
anc = ace(y, sim.tree)
cat(&quot;The ancestral state is estimated to be:&quot;, round(anc$ace[1], 2), &quot;\n&quot;,
    &quot;With a 95% CI of:&quot;, round(anc$CI95[1,], 3))</code></pre>
<pre><code>## The ancestral state is estimated to be: 4.38 
##  With a 95% CI of: 2.466 6.297</code></pre>
<p>The default ancestral state model is Brownian motion, and it does a pretty good job at estimating our known ancestral state of 5. This coding procedure is pretty simple, and to code the same results in INLA is quite complicated, so you may ask why we need something more complicated, which I will discuss at the end.</p>
<p>Next, we code the same model up using INLA, which requires a small amount of data wrangling:</p>
<pre class="r"><code>library(INLA)
library(stringr)

# INLA requires the data as a dataframe. 
model_df = data.frame(label = names(y), y = y)</code></pre>
<p>As discussed in my previous INLA post, INLA requires a precision matrix. In this instance, I use <code>nodes = "ALL"</code> rather than <code>nodes = "TIPS"</code>. This means we include the relationships between all taxa and all nodes. We will use the information between nodes in the phylogeny to reconstruct our ancestral state.</p>
<pre class="r"><code># INLA also requires the relationships between data to be 
# precision matrix
prec_mat = MCMCglmm::inverseA(sim.tree,
                   nodes = &quot;ALL&quot;,
                   scale = FALSE)$Ainv</code></pre>
<p>As with many regression based functions, we will introduce the data we want to reconstruct using a dataframe. In the case of reconstruction, we will not only include rows in the dataframe for each observed datapoint (in this case extant taxa), but also for the unobserved points we want to reconstruct (the internal nodes and root of the phylogeny). The unknown data will be respresented with missing / NA values. In the next block of code I also create an index to match the rows of the dataframe to the rows of the precision matrix.</p>
<pre class="r"><code># add in node data
node_idx = str_detect(rownames(prec_mat), &quot;Node&quot;)
node_df = data.frame(label = rownames(prec_mat)[node_idx], 
                     y = NA)

model_df = rbind(model_df, node_df)

# Create matching index
model_df$phylo_id = match(model_df$label, rownames(prec_mat))</code></pre>
<p>Now it is time to put it all together to calculate the ancestral states. To learn more about the construction of INLA models see <a href="/post/2022-07-15-phylogenetic-signal-in-inla">my earlier post</a>, or go to <a href="https://www.r-inla.org/">the INLA webpage</a>. A new argument in this this model is <code>control.predictor=list(compute=TRUE)</code>. This tells the model to predict the values which are missing in the response. In our case, there are the internal nodes.</p>
<pre class="r"><code>fit = inla(y ~ f(phylo_id,
                 model = &quot;generic0&quot;,
                 Cmatrix = prec_mat), 
           data = model_df, 
           control.predictor=list(compute = TRUE),
           control.compute=list(config = TRUE)
           )


cat(&quot;The ancestral state is estimated to be:&quot;, round(fit$summary.fitted.values[101,1], 2), &quot;\n&quot;,
    &quot;With a 95% CI of:&quot;, unlist(round(fit$summary.fitted.values[101,c(3,5)], 3)))</code></pre>
<pre><code>## The ancestral state is estimated to be: 5.39 
##  With a 95% CI of: 4.222 6.552</code></pre>
<p>Recall that the <code>ape::ace</code> function estimated the mean to be 4.38 (95% CI: 2.47 - 6.3). Both approaches are close to the ancestral state (5), but INLA is closer and providing a narrower confidence interval. Comparatively, the INLA approach is more fiddly, but is providing us with less error, so there is some reward for the time, however there are two more benefits worth looking at. The first benefit is that INLA is a Bayesian approach, and being a Bayesian approach means we can also plot the posterior predictive distribution of the results, providing a clearer view of the error distribution:</p>
<pre class="r"><code>post = INLA::inla.posterior.sample(1000, fit)
anc.post = lapply(post, function(p) p$latent[101]) %&gt;% 
  unlist()

plot(density(anc.post), main = &quot;Posterior distribution of Ancestral State estimates&quot;,
     xlab = &quot;Ancestral state Estimate&quot;, col = &quot;blue&quot;, 
     xlim = range(y))
abline(v = 5, lty = &quot;longdash&quot;, lwd = 2, col = &quot;black&quot;)
text(x = 4.9, y = 0.2, label = &quot;True Ancestral State&quot;, srt = 90)
abline(v = unlist(fit$summary.fitted.values[101,1]), lty = &quot;dotdash&quot;, lwd = 2, col = &quot;blue&quot;)
text(x = unlist(fit$summary.fitted.values[101,1]) - 0.1, y = 0.2, label = &quot;INLA Estimate&quot;, srt = 90)
# abline(v = unlist(fit$summary.fitted.values[101,c(3,5)]), lty = &quot;dashed&quot;, col = &quot;blue&quot;)
abline(v = anc$ace[1], lty = &quot;dotdash&quot;, lwd = 2, col = &quot;red&quot;)
text(x = anc$ace[1] - 0.1, y = 0.2, label = &quot;ape::ace Estimate&quot;, srt = 90)
abline(v = anc$CI95[1,], lty = &quot;dashed&quot;, col = &quot;red&quot;)
text(x = anc$CI95[1,] - 0.1, y = 0.2, label = &quot;ape::ace 95% CI&quot;, srt = 90)</code></pre>
<p><img src="https://www.sampassmore.com/post/2023-02-10-ancestral-state-reconstruction-with-inla/index_files/figure-html/unnamed-chunk-6-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The graph above exemplifies the difference in error and provides a clear visualization of the INLA model’s prediction. From here, we could tweak priors to try and improve the estimate and errors of the model.</p>
<p>A second advantage of the INLA approach is that we can accomodate other factors into the model that we think might influence the ancestral state other than the phylogenetic history. For example, environmental factors may influence the current state of traits. I may extend this example in the future to accommodate such a possibility.</p>
</div>
        <div class="post-footer">
            <div class="info">
                
                
            </div>
        </div>

        
    </div>


        </div>
    </div>
</div>

<script type="text/javascript"
        src="https://www.sampassmore.com/js/jquery.min.fbe301dd6883c65e7239a10ab4a0bf2fac3d44a19284226d4062b0c7d773c46a.js"
        integrity="sha256-&#43;&#43;MB3WiDxl5yOaEKtKC/L6w9RKGShCJtQGKwx9dzxGo="
        crossorigin="anonymous"></script>




<script type="text/javascript"
        src="https://www.sampassmore.com/js/bundle.min.851d092fdf9f79a0ad4f9d05360d0928fd8f817b7f5df84a4e1a43dc936bc398.js"
        integrity="sha256-hR0JL9&#43;feaCtT50FNg0JKP2PgXt/XfhKThpD3JNrw5g="
        crossorigin="anonymous"></script>

<script type="text/javascript"
        src="https://www.sampassmore.com/js/medium-zoom.min.c5719dbaf0204e654acaebc2ae8b75cfadec34b88aeca3a0da573a3a7eccdc2a.js"
        integrity="sha256-xXGduvAgTmVKyuvCrot1z63sNLiK7KOg2lc6On7M3Co="
        crossorigin="anonymous"></script>
</body>

</html>
